[tool.mypy]
files = ["app/src", "app/tests"]
ignore_missing_imports = true
strict = true
exclude = ["venv/"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip_glob = "migrations/*"
